name: PlayerJoinSettings
main: com.github.anders2333.PlayerJoinSettings
api: ["1.0.8"]
version: "1.0.0"
author: Anders
load: POSTWORLD
commands:
  uiset:
    description: "进服弹出UI设置"
    permission: "PlayerJoinSettings.Command.UISet"
    usage: "/uiset help"
permissions:
  PlayerJoinSettings.Command.UISet:
    description: "允许使用指令： /uiset"
    default: op